### ISSUE TITLE
Future of this project?

### ISSUE THREAD

**Issue by ghost** [go-kivik/mango#24]
Hello @flimzy, 

I've been reviewing CouchDB for inclusion in a project of mine and in the process I discovered your excellent driver [kivik](https://github.com/go-kivik/kivik.git). 

While reviewing the above, I discovered this project. Now, **mango** seems like something I'd want to use, however the **Issues** section is sprinkled with "reminder" tickets opened in 2017 regarding missing **Mango** operators support.

Are there any plans on implementing the missing functionality and adding some documentation to the project, or it's safe to consider it dead for any practical purpose?

Regards.

**Comment by flimzy** [comment]
Kivik is active, and supported, with complete support for Mango queries against CouchDB. This package, however, is unrelated to that. The purpose of this package is to do Mango-compatable queries against raw JSON documents, as stored on a filesystem.

**Comment by ghost** [comment]
Thank you @flimzy .
